# docker-compose.yml
version: '3'

services:
  flaskapp:
    build: .
    volumes:
      - ./app:/app/
      - db_data:/app/users.db 
    env_file: ".env"
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.flaskapp.entrypoints: websecure
      traefik.http.routers.flaskapp.rule: 'Host(`app.alkemata.com`)'
      traefik.http.services.flaskapp.loadbalancer.server.port: 5000
    networks:
      - traefik_web


networks:
  traefik_web:
    external: true
