# docker-compose.yml
version: '3'

services:
  web:
    build: .
    volumes:
      - ./app:/app/
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.wordpress.entrypoints: websecure
      traefik.http.routers.wordpress.rule: 'Host(`app.alkemata.com`)'
      traefik.http.services.wordpress.loadbalancer.server.port: 5000
    networks:
      - traefik_web


networks:
  traefik_web:
    external: true
