# docker-compose.yml
version: '3'

services:
  flaskapp:
    build: .
    volumes:
      - ./app:/app/
    ports: 
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.flaskapp.entrypoints: websecure
      traefik.http.routers.flaskapp.rule: 'Host(`app.alkemata.com`)'
      traefik.http.services.flaskapp.loadbalancer.server.port: 5000
    networks:
      - traefik_web


networks:
  traefik_web:
    external: true
